"""API functions related to institutions."""

import re

from typing import Annotated, Any, Dict, Optional, Tuple, cast
from fastapi import HTTPException, status, APIRouter, Depends
from pydantic import BaseModel
from sqlalchemy.orm import Session
from sqlalchemy.future import select
from sqlalchemy import and_, delete, func

from ..utilities import (
    has_access_to_inst_or_err,
    has_at_most_one_school_type,
    BaseUser,
    AccessType,
    get_external_bucket_name_from_uuid,
    str_to_uuid,
    uuid_to_str,
    get_current_active_user,
    SchemaType,
    PDP_SCHEMA_GROUP,
    EDVISE_SCHEMA_GROUP,
    LEGACY_SCHEMA_GROUP,
    UsState,
    get_external_bucket_name,
)

from ..gcsutil import StorageControl
from ..database import (
    get_session,
    InstTable,
    local_session,
)

from ..databricks import DatabricksControl

router = APIRouter(
    tags=["institutions"],
)

# PATCH/POST: every institution must resolve to exactly one school type (IDs on the row).
_EXACTLY_ONE_SCHOOL_TYPE_DETAIL = (
    "Institution must be exactly one of PDP (set pdp_id), "
    "Edvise Schema (ES) (set edvise_id or is_edvise), or Legacy "
    "(set legacy_id or is_legacy)."
)
_MUTUALLY_EXCLUSIVE_SCHOOL_TYPE_DETAIL = (
    "An institution cannot be more than one of PDP, Edvise Schema (ES), or Legacy. "
    "Please choose one schema type."
)


class InstitutionCreationRequest(BaseModel):
    """Institution data creation request.

    The UUID is autogenerated by the database.
    """

    # The name should be unique amongst all other institutions.
    name: str | None = None
    state: UsState | None = None
    allowed_schemas: list[SchemaType] | None = None
    # Emails allowed to register under this institution
    allowed_emails: Dict[str, AccessType] | None = None
    # The following is a shortcut to specifying the allowed_schemas list and will mean
    # that the allowed_schemas will be augmented with the PDP_SCHEMA_GROUP.
    # Note: is_pdp is kept for backward compatibility but is ignored. PDP status is derived from pdp_id presence.
    is_pdp: bool | None = None
    pdp_id: str | None = None
    # Note: is_edvise is kept for backward compatibility. When True and edvise_id is omitted, edvise_id is auto-assigned.
    is_edvise: bool | None = None
    edvise_id: str | None = None
    # Legacy schools: upload data in any format. When True and legacy_id is omitted, legacy_id is auto-assigned.
    is_legacy: bool | None = None
    legacy_id: str | None = None
    retention_days: int | None = None


class Institution(BaseModel):
    """Institution data object."""

    inst_id: str
    name: str
    state: UsState | None = None
    # The following are characteristics of an institution set at institution creation time.
    # If zero, it follows DK defaults (deletion after completion).
    retention_days: int | None = None  # In Days
    pdp_id: str | None = None
    edvise_id: str | None = None
    legacy_id: str | None = None


@router.get("/institutions", response_model=list[Institution])
def read_all_inst(
    current_user: Annotated[BaseUser, Depends(get_current_active_user)],
    sql_session: Annotated[Session, Depends(get_session)],
) -> Any:
    """Returns overview data on all institutions.

    Only visible to Datakinders.
    """
    if not current_user.is_datakinder():
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Not authorized to read this resource. Select a specific institution.",
        )
    local_session.set(sql_session)
    query_result = local_session.get().execute(select(InstTable))
    res = []
    for elem in query_result:
        res.append(
            {
                "inst_id": uuid_to_str(elem[0].id),
                "name": elem[0].name,
                "state": elem[0].state,
                "retention_days": elem[0].retention_days,
                "pdp_id": None if elem[0].pdp_id is None else elem[0].pdp_id,
                "edvise_id": None if elem[0].edvise_id is None else elem[0].edvise_id,
                "legacy_id": None if elem[0].legacy_id is None else elem[0].legacy_id,
            }
        )
    return res


def _request_has_more_than_one_school_type(
    req: InstitutionCreationRequest,
    pdp_id: Optional[str],
    edvise_id: Optional[str],
    legacy_id: Optional[str],
) -> bool:
    """Return True if the request indicates more than one of PDP, Edvise Schema (ES), or Legacy."""
    pdp_set = bool(pdp_id)
    edvise_set = bool(req.is_edvise) or bool(edvise_id)
    legacy_set = bool(req.is_legacy) or bool(legacy_id)
    return (pdp_set + edvise_set + legacy_set) > 1


def _compute_edvise_legacy_ids_for_create(
    sess: Session,
    req: InstitutionCreationRequest,
    edvise_id: Optional[str],
    legacy_id: Optional[str],
) -> Tuple[Optional[str], Optional[str]]:
    """Auto-assign edvise_id or legacy_id when type is set but no id provided. Returns (edvise_id, legacy_id)."""
    if req.is_edvise and not edvise_id:
        count = (
            sess.execute(
                select(func.count())
                .select_from(InstTable)
                .where(InstTable.edvise_id.isnot(None))
            ).scalar()
            or 0
        )
        edvise_id = f"edvise_{count + 1}"
    if req.is_legacy and not legacy_id:
        count = (
            sess.execute(
                select(func.count())
                .select_from(InstTable)
                .where(InstTable.legacy_id.isnot(None))
            ).scalar()
            or 0
        )
        legacy_id = f"legacy_{count + 1}"
    return (edvise_id, legacy_id)


def _raise_if_existing_row_invalid_for_duplicate_post(existing: InstTable) -> None:
    """Reject idempotent POST when the stored row violates school-type invariants."""
    ep, ee, el = existing.pdp_id, existing.edvise_id, existing.legacy_id
    if not has_at_most_one_school_type(ep, ee, el):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=_MUTUALLY_EXCLUSIVE_SCHOOL_TYPE_DETAIL,
        )
    if sum(bool(x) for x in (ep, ee, el)) != 1:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=(
                "An institution with this name and state already exists but does not "
                "have a valid school type configured. "
                + _EXACTLY_ONE_SCHOOL_TYPE_DETAIL
            ),
        )


def _raise_if_institution_name_patch_disallowed(
    update_data: dict, existing_name: str
) -> None:
    if "name" in update_data and update_data["name"] != existing_name:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Institution names cannot be changed.",
        )


def _normalize_patch_school_id_strings(update_data: dict) -> None:
    for key in ("pdp_id", "edvise_id", "legacy_id"):
        if key in update_data:
            update_data[key] = (update_data[key] or "").strip() or None


def _resolve_merged_school_type_triple_for_patch(
    existing_inst: InstTable,
    update_data: dict,
    sess: Session,
) -> Tuple[Optional[str], Optional[str], Optional[str], bool]:
    """Merge PATCH school-type fields, auto-assign ids, enforce exactly one type."""
    old_type_triple = (
        existing_inst.pdp_id,
        existing_inst.edvise_id,
        existing_inst.legacy_id,
    )
    _raise_if_institution_name_patch_disallowed(update_data, existing_inst.name)
    _normalize_patch_school_id_strings(update_data)
    final_pdp_id = (
        update_data["pdp_id"] if "pdp_id" in update_data else existing_inst.pdp_id
    )
    final_edvise_id = (
        update_data["edvise_id"]
        if "edvise_id" in update_data
        else existing_inst.edvise_id
    )
    final_legacy_id = (
        update_data["legacy_id"]
        if "legacy_id" in update_data
        else existing_inst.legacy_id
    )
    if _patch_indicates_more_than_one_school_type(
        update_data, final_pdp_id, final_edvise_id, final_legacy_id
    ):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=_MUTUALLY_EXCLUSIVE_SCHOOL_TYPE_DETAIL,
        )
    final_edvise_id, final_legacy_id = _compute_edvise_legacy_ids_for_patch(
        sess, update_data, final_edvise_id, final_legacy_id
    )
    if not has_at_most_one_school_type(final_pdp_id, final_edvise_id, final_legacy_id):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=_MUTUALLY_EXCLUSIVE_SCHOOL_TYPE_DETAIL,
        )
    if sum(bool(x) for x in (final_pdp_id, final_edvise_id, final_legacy_id)) != 1:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=_EXACTLY_ONE_SCHOOL_TYPE_DETAIL,
        )
    school_type_changed = old_type_triple != (
        final_pdp_id,
        final_edvise_id,
        final_legacy_id,
    )
    return final_pdp_id, final_edvise_id, final_legacy_id, school_type_changed


def _require_single_institution_row_by_uuid(sess: Session, inst_id: str) -> InstTable:
    """Load exactly one InstTable row by UUID or raise HTTP 400."""
    query_result = (
        sess.execute(
            select(InstTable).where(InstTable.id == str_to_uuid(inst_id))
        ).all()
    )
    if not query_result or len(query_result) != 1:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Unexpected number of institutions found with this id. Expected 1 got "
            + str(len(query_result)),
        )
    return cast(InstTable, query_result[0][0])


def _persist_institution_patch_row_fields(
    existing_inst: InstTable,
    update_data: dict,
    final_pdp_id: Optional[str],
    final_edvise_id: Optional[str],
    final_legacy_id: Optional[str],
) -> None:
    """Apply non-schema PATCH fields and the resolved school-type triple to the ORM row."""
    if "state" in update_data:
        existing_inst.state = update_data["state"]
    if "allowed_emails" in update_data:
        existing_inst.allowed_emails = update_data["allowed_emails"]
    if "retention_days" in update_data:
        existing_inst.retention_days = update_data["retention_days"]
    existing_inst.pdp_id = final_pdp_id
    existing_inst.edvise_id = final_edvise_id
    existing_inst.legacy_id = final_legacy_id


def _apply_institution_schema_updates_from_patch(
    existing_inst: InstTable,
    update_data: dict,
    school_type_changed: bool,
    final_pdp_id: Optional[str],
    final_edvise_id: Optional[str],
    final_legacy_id: Optional[str],
) -> None:
    if school_type_changed:
        extra_allowed = (
            update_data["allowed_schemas"]
            if "allowed_schemas" in update_data
            else None
        )
        existing_inst.schemas = _build_requested_schemas(
            extra_allowed,
            final_pdp_id,
            final_edvise_id,
            final_legacy_id,
        )
    elif "allowed_schemas" in update_data:
        existing_inst.schemas = update_data["allowed_schemas"]


def _patch_indicates_more_than_one_school_type(
    update_data: dict,
    pdp_id: Optional[str],
    edvise_id: Optional[str],
    legacy_id: Optional[str],
) -> bool:
    """True if merged IDs plus explicit is_edvise/is_legacy flags imply more than one school type."""
    pdp_set = bool(pdp_id)
    edvise_flag = (
        update_data["is_edvise"] if "is_edvise" in update_data else False
    )
    legacy_flag = (
        update_data["is_legacy"] if "is_legacy" in update_data else False
    )
    edvise_set = bool(edvise_id) or bool(edvise_flag)
    legacy_set = bool(legacy_id) or bool(legacy_flag)
    return (pdp_set + edvise_set + legacy_set) > 1


def _compute_edvise_legacy_ids_for_patch(
    sess: Session,
    update_data: dict,
    edvise_id: Optional[str],
    legacy_id: Optional[str],
) -> Tuple[Optional[str], Optional[str]]:
    """Auto-assign edvise_id/legacy_id when PATCH sets is_edvise/is_legacy True and id is still empty."""
    if update_data.get("is_edvise") and not edvise_id:
        count = (
            sess.execute(
                select(func.count())
                .select_from(InstTable)
                .where(InstTable.edvise_id.isnot(None))
            ).scalar()
            or 0
        )
        edvise_id = f"edvise_{count + 1}"
    if update_data.get("is_legacy") and not legacy_id:
        count = (
            sess.execute(
                select(func.count())
                .select_from(InstTable)
                .where(InstTable.legacy_id.isnot(None))
            ).scalar()
            or 0
        )
        legacy_id = f"legacy_{count + 1}"
    return (edvise_id, legacy_id)


def _build_requested_schemas(
    allowed_schemas: Optional[list],
    pdp_id: Optional[str],
    edvise_id: Optional[str],
    legacy_id: Optional[str],
) -> list:
    """Merge optional explicit allowed_schemas with the schema group for the school type.

    Callers must ensure exactly one of pdp_id, edvise_id, or legacy_id is set;
    the merged groups are always non-empty.
    """
    requested_schemas = list(allowed_schemas) if allowed_schemas else []
    if pdp_id:
        requested_schemas += list(PDP_SCHEMA_GROUP)
    if edvise_id:
        requested_schemas += list(EDVISE_SCHEMA_GROUP)
    if legacy_id:
        requested_schemas += list(LEGACY_SCHEMA_GROUP)
    return list(set(requested_schemas))


def _build_requested_schemas_for_create(
    req: InstitutionCreationRequest,
    pdp_id: Optional[str],
    edvise_id: Optional[str],
    legacy_id: Optional[str],
) -> list:
    """Build the requested_schemas list from req and school-type IDs (same rules as PATCH)."""
    return _build_requested_schemas(
        req.allowed_schemas, pdp_id, edvise_id, legacy_id
    )


def _validate_and_prepare_create_institution(
    req: InstitutionCreationRequest,
    current_user: BaseUser,
    sql_session: Session,
) -> Tuple[Session, Optional[str], Optional[str], Optional[str]]:
    """
    Validate request and compute normalized IDs. Returns (sess, pdp_id, edvise_id, legacy_id).
    Raises HTTPException on validation failure.
    """
    if not current_user.is_datakinder():
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Not authorized to create an institution.",
        )
    if not req.name:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Please set the institution name.",
        )
    if not re.match(r"^[A-Za-z0-9&_ -]*$", req.name):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Only alphanumeric characters, -, _, &, and a space are allowed in institution names.",
        )
    pdp_id = (req.pdp_id or "").strip() or None
    edvise_id = (req.edvise_id or "").strip() or None
    legacy_id = (req.legacy_id or "").strip() or None

    if _request_has_more_than_one_school_type(req, pdp_id, edvise_id, legacy_id):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=_MUTUALLY_EXCLUSIVE_SCHOOL_TYPE_DETAIL,
        )
    local_session.set(sql_session)
    sess = local_session.get()
    edvise_id, legacy_id = _compute_edvise_legacy_ids_for_create(
        sess, req, edvise_id, legacy_id
    )
    if not has_at_most_one_school_type(pdp_id, edvise_id, legacy_id):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=_MUTUALLY_EXCLUSIVE_SCHOOL_TYPE_DETAIL,
        )
    school_type_count = sum(bool(x) for x in (pdp_id, edvise_id, legacy_id))
    if school_type_count != 1:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=_EXACTLY_ONE_SCHOOL_TYPE_DETAIL,
        )
    return (sess, pdp_id, edvise_id, legacy_id)


def _institution_row_to_response(row: Any) -> Dict[str, Any]:
    """Build the Institution response dict from an InstTable row."""
    return {
        "inst_id": uuid_to_str(row.id),
        "name": row.name,
        "state": row.state,
        "pdp_id": row.pdp_id,
        "edvise_id": row.edvise_id,
        "legacy_id": row.legacy_id,
        "retention_days": row.retention_days,
    }


def _create_institution_record_and_infrastructure(
    sess: Session,
    req: InstitutionCreationRequest,
    pdp_id: Optional[str],
    edvise_id: Optional[str],
    legacy_id: Optional[str],
    requested_schemas: list,
    current_user: BaseUser,
    storage_control: StorageControl,
    databricks_control: DatabricksControl,
) -> Any:
    """
    Add institution record, commit, create bucket and Databricks setup. Returns the created InstTable row.
    Raises HTTPException on failure.
    """
    sess.add(
        InstTable(
            name=req.name,
            retention_days=req.retention_days,
            pdp_id=pdp_id,
            edvise_id=edvise_id,
            legacy_id=legacy_id,
            schemas=requested_schemas,
            allowed_emails=req.allowed_emails,
            state=req.state,
            created_by=str_to_uuid(current_user.user_id),
        )
    )
    sess.commit()
    query_result = sess.execute(
        select(InstTable).where(InstTable.name == req.name)
    ).all()
    if not query_result:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Database write of the institution creation failed.",
        )
    if len(query_result) > 1:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Database write of the institution created duplicate entries.",
        )
    inst_row = query_result[0][0]
    bucket_name = get_external_bucket_name_from_uuid(inst_row.id)
    try:
        storage_control.create_bucket(bucket_name)
    except ValueError as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Storage bucket creation failed:" + str(e),
        ) from e
    try:
        databricks_control.setup_new_inst(inst_row.name)
    except Exception as e:
        # DatabricksControl may raise various exceptions; catch and re-raise with context.
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Databricks setup failed:" + str(e),
        ) from e
    return inst_row


@router.post("/institutions", response_model=Institution)
def create_institution(
    req: InstitutionCreationRequest,
    current_user: Annotated[BaseUser, Depends(get_current_active_user)],
    sql_session: Annotated[Session, Depends(get_session)],
    storage_control: Annotated[StorageControl, Depends(StorageControl)],
    databricks_control: Annotated[DatabricksControl, Depends(DatabricksControl)],
) -> Any:
    """Create a new institution. Only available to Datakinders."""
    sess, pdp_id, edvise_id, legacy_id = _validate_and_prepare_create_institution(
        req, current_user, sql_session
    )
    query_result = sess.execute(
        select(InstTable).where(
            and_(InstTable.name == req.name, InstTable.state == req.state)
        )
    ).all()
    if len(query_result) == 0:
        requested_schemas = _build_requested_schemas_for_create(
            req, pdp_id, edvise_id, legacy_id
        )
        row = _create_institution_record_and_infrastructure(
            sess,
            req,
            pdp_id,
            edvise_id,
            legacy_id,
            requested_schemas,
            current_user,
            storage_control,
            databricks_control,
        )
    else:
        existing = query_result[0][0]
        _raise_if_existing_row_invalid_for_duplicate_post(existing)
        row = existing
    if len(query_result) > 1:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Institution duplicates found.",
        )
    return _institution_row_to_response(row)


@router.patch("/institutions/{inst_id}", response_model=Institution)
def update_inst(
    inst_id: str,
    request: InstitutionCreationRequest,
    current_user: Annotated[BaseUser, Depends(get_current_active_user)],
    sql_session: Annotated[Session, Depends(get_session)],
) -> Any:
    """Modifies an existing institution.

    The row must keep exactly one of pdp_id, edvise_id, or legacy_id (same as POST).
    ``is_edvise`` / ``is_legacy`` in the body trigger the same auto-id assignment as
    POST when the corresponding id is still empty after merging with the existing row.

    ``schemas`` is recomputed (like POST) only when the school-type triple actually
    changes; ``allowed_schemas`` alone still replaces ``schemas`` when no type change.
    """
    if not current_user.is_datakinder():
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Not authorized to modify an institution.",
        )
    update_data = request.model_dump(exclude_unset=True)
    local_session.set(sql_session)
    sess = local_session.get()
    existing_inst = _require_single_institution_row_by_uuid(sess, inst_id)
    (
        final_pdp_id,
        final_edvise_id,
        final_legacy_id,
        school_type_changed,
    ) = _resolve_merged_school_type_triple_for_patch(
        existing_inst, update_data, sess
    )
    _persist_institution_patch_row_fields(
        existing_inst,
        update_data,
        final_pdp_id,
        final_edvise_id,
        final_legacy_id,
    )
    _apply_institution_schema_updates_from_patch(
        existing_inst,
        update_data,
        school_type_changed,
        final_pdp_id,
        final_edvise_id,
        final_legacy_id,
    )
    sess.commit()
    refreshed = _require_single_institution_row_by_uuid(sess, inst_id)
    return _institution_row_to_response(refreshed)


@router.delete("/institutions/{inst_id}", response_model=None)
def delete_inst(
    inst_id: str,
    current_user: Annotated[BaseUser, Depends(get_current_active_user)],
    sql_session: Annotated[Session, Depends(get_session)],
    storage_control: Annotated[StorageControl, Depends(StorageControl)],
    databricks_control: Annotated[DatabricksControl, Depends(DatabricksControl)],
) -> Any:
    """Delete an existing institution.

    Only available to Datakinders.
    """
    if not current_user.is_datakinder():
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Not authorized to delete an institution.",
        )

    local_session.set(sql_session)
    query_result = (
        local_session.get()
        .execute(select(InstTable).where(InstTable.id == str_to_uuid(inst_id)))
        .all()
    )
    if len(query_result) != 1:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Unexpected number of institutions found. Expected 1 got "
            + str(len(query_result)),
        )
    inst_name = query_result[0][0].name
    local_session.get().execute(
        delete(InstTable).where(InstTable.id == str_to_uuid(inst_id))
    )
    local_session.get().commit()
    # Delete GCS bucket
    bucket_name = get_external_bucket_name(inst_id)
    try:
        storage_control.delete_bucket(bucket_name)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Storage bucket deletion failed:" + str(e),
        ) from e
    # Delete all databricks managed pieces.
    try:
        databricks_control.delete_inst(inst_name)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Databricks deletion failed:" + str(e),
        ) from e


# All other API transactions require the UUID as an identifier, this allows the UUID lookup by human readable name.
@router.get("/institutions/name/{inst_name}", response_model=Institution)
def read_inst_name(
    inst_name: str,
    current_user: Annotated[BaseUser, Depends(get_current_active_user)],
    sql_session: Annotated[Session, Depends(get_session)],
) -> Any:
    """Returns overview data on a specific institution.

    The root-level API view. Only visible to users of that institution or Datakinder access types.

    Note: Name matching is case-insensitive. The function will match institution names
    regardless of the case of the input parameter. If multiple institutions with the same
    name (case-insensitive) exist, this will raise an error.
    """
    local_session.set(sql_session)
    query_result = (
        local_session.get()
        .execute(
            select(InstTable).where(func.lower(InstTable.name) == func.lower(inst_name))
        )
        .all()
    )

    if len(query_result) == 0:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Institution not found.",
        )
    if len(query_result) > 1:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Institution duplicates found.",
        )
    has_access_to_inst_or_err(uuid_to_str(query_result[0][0].id), current_user)
    return {
        "inst_id": uuid_to_str(query_result[0][0].id),
        "name": query_result[0][0].name,
        "retention_days": query_result[0][0].retention_days,
        "state": query_result[0][0].state,
        "pdp_id": query_result[0][0].pdp_id,
        "edvise_id": query_result[0][0].edvise_id,
        "legacy_id": query_result[0][0].legacy_id,
    }


# All other API transactions require the UUID as an identifier, this allows the UUID lookup by PDP ID.
@router.get("/institutions/pdp-id/{pdp_id}", response_model=Institution)
def read_inst_pdp_id(
    pdp_id: str,
    current_user: Annotated[BaseUser, Depends(get_current_active_user)],
    sql_session: Annotated[Session, Depends(get_session)],
) -> Any:
    """Returns the uuid for a school given its pdp_id. Endpoint allowed for any user."""
    local_session.set(sql_session)
    query_result = (
        local_session.get()
        .execute(select(InstTable).where(InstTable.pdp_id == pdp_id))
        .all()
    )
    if len(query_result) == 0:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Institution not found.",
        )
    if len(query_result) > 1:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Institution duplicates found.",
        )
    has_access_to_inst_or_err(uuid_to_str(query_result[0][0].id), current_user)
    return {
        "inst_id": uuid_to_str(query_result[0][0].id),
        "name": query_result[0][0].name,
        "retention_days": query_result[0][0].retention_days,
        "state": query_result[0][0].state,
        "pdp_id": query_result[0][0].pdp_id,
        "edvise_id": query_result[0][0].edvise_id,
        "legacy_id": query_result[0][0].legacy_id,
    }


@router.get("/institutions/{inst_id}", response_model=Institution)
def read_inst_id(
    inst_id: str,
    current_user: Annotated[BaseUser, Depends(get_current_active_user)],
    sql_session: Annotated[Session, Depends(get_session)],
) -> Any:
    """Returns overview data on a specific institution.

    The root-level API view. Only visible to users of that institution or Datakinder access types.
    """
    has_access_to_inst_or_err(inst_id, current_user)
    local_session.set(sql_session)
    query_result = (
        local_session.get()
        .execute(select(InstTable).where(InstTable.id == str_to_uuid(inst_id)))
        .all()
    )
    if not query_result or len(query_result) == 0:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Institution not found.",
        )
    if len(query_result) > 1:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Institution duplicates found.",
        )
    return {
        "inst_id": uuid_to_str(query_result[0][0].id),
        "name": query_result[0][0].name,
        "retention_days": query_result[0][0].retention_days,
        "state": query_result[0][0].state,
        "pdp_id": query_result[0][0].pdp_id,
        "edvise_id": query_result[0][0].edvise_id,
        "legacy_id": query_result[0][0].legacy_id,
    }
